In [2]:
import numpy as np

In [4]:
arr=np.array([[1,2,3],[4,5,6]])

In [5]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
type(arr)

numpy.ndarray

In [7]:
r=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [8]:
print(r)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [9]:
type(r)

numpy.ndarray

In [10]:
print(arr.ndim)

2


In [11]:
import numpy
e=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(e.ndim)

2


In [13]:
print(e.shape)

(3, 3)


In [31]:
import numpy
f=numpy.array([1,2,3,4,5],dtype='float')
print(f)

[1. 2. 3. 4. 5.]


In [15]:
print(f.ndim)

1


In [16]:
print(f.shape)

(5,)


In [17]:
g=numpy.array([[1,2,3],[4,5,6]])
print(g)
print(g.shape)
print(g.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [18]:
print(g.size)

6


In [19]:
print(g.dtype)

int32


In [20]:
import numpy
y=numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(y)
print(y.shape)
print(y.ndim)
print(y.dtype)
print(y.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(5, 3)
2
int32
15


In [23]:
e=numpy.array([[1,2,3,4],[5,6,7,8]],dtype='float')
print(e)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [24]:
print(type(e))

<class 'numpy.ndarray'>


In [25]:
print(type([[1,2,3,4],[5,6,7,8]]))

<class 'list'>


In [26]:
print(type([[1,2],[3,4]]))

<class 'list'>


In [32]:
import numpy
t=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(t)
print(t.size)
print(t.shape)
print(t.ndim)
print(t.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
2
int32


In [34]:
import numpy
t=numpy.array([[1,2],[3,4],[5,6]],dtype='int')
print(t)

[[1 2]
 [3 4]
 [5 6]]


In [35]:
import numpy
a=numpy.array((1,2,3,4))
print(a)

[1 2 3 4]


In [38]:
import numpy
b=numpy.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
import random
print(random.random())
print(random.randint(1,3))

0.3684033573570633
3


In [48]:
import numpy
q=numpy.ones((3,5))
print(q)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
import numpy
q=numpy.eye(4)
print(q)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [50]:
import numpy
q=numpy.ones?

In [52]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [53]:
import numpy
r=numpy.linspace?

In [54]:
import numpy
print(numpy.linspace(0,5,10))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [68]:
import numpy
a=numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
w=a.reshape((3,4))
print(w)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [69]:
import numpy
w=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
x=w.flatten()
print(x)

[1 2 3 4 5 6 7 8 9]


In [70]:
import numpy
r=numpy.array([[-1,2,0,4],[4,-5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print(r)

[[-1.   2.   0.   4. ]
 [ 4.  -5.   6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [74]:
print(r[1:,:3])

[[ 4.  -5.   6. ]
 [ 2.6  0.   7. ]
 [ 3.  -7.   4. ]]


In [78]:
print(r[1:4:2,1:4:2])

[[-5.  0.]
 [-7.  2.]]


In [79]:
import numpy
t=numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(t+1)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


In [80]:
import numpy
e=numpy.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(e+1)
print(e-1)
print(e*2)
print(e/2)
print(e%2)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
[[0.5 1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5 5. ]
 [5.5 6.  6.5 7.  7.5]]
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [83]:
import numpy
a=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [96]:
import numpy
r=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(r)
print("Max element of array is ",r.max())
print("Min element of array is ",r.min())
print("Sum of all elements of the array is ",r.sum())
print("Column wise Max: ",r.max(axis=0))
print("Row wise max elements: ",r.max(axis=1))
print("cumulative sum along each row: ",r.cumsum(axis=1))
print("Cumulative sum along each column: ",r.cumsum(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Max element of array is  9
Min element of array is  1
Sum of all elements of the array is  45
Column wise Max:  [7 8 9]
Row wise max elements:  [3 6 9]
cumulative sum along each row:  [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
Cumulative sum along each column:  [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [102]:
import numpy
a=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
b=numpy.array([[9,8,7],[6,5,4],[3,2,1]])
print(a+b)
print(a-b)
print(a*b)#Corresponding elements are multiplied
print(a.dot(b))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [103]:
import numpy
a=numpy.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [106]:
b=numpy.array([0,numpy.pi/2,numpy.pi])
print(b)

[0.         1.57079633 3.14159265]


In [107]:
c=numpy.array([1,2,3])
print(numpy.exp(c))

[ 2.71828183  7.3890561  20.08553692]


In [108]:
d=numpy.array([1,2,3])
print(numpy.sqrt(d))

[1.         1.41421356 1.73205081]


In [114]:
import numpy
a=numpy.array([[1,40,2],[5,4,9],[9,90,5]])
a=numpy.sort(a,axis=1)
print(a)

[[ 1  2 40]
 [ 4  5  9]
 [ 5  9 90]]


In [115]:
a=numpy.sort(a,axis=0)
print(a)

[[ 1  2  9]
 [ 4  5 40]
 [ 5  9 90]]


In [116]:
print(numpy.sort(a))

[[ 1  2  9]
 [ 4  5 40]
 [ 5  9 90]]


In [126]:
import numpy
a=numpy.array([[1,2],[3,4]])
b=numpy.array([[5,6],[7,8]])
c=numpy.array([98,99])
print(numpy.vstack((a,b)))
print(numpy.hstack((a,b)))
print(numpy.column_stack((a,c)))
print(numpy.concatenate((a,b),0))
print(numpy.concatenate((a,b),1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[ 1  2 98]
 [ 3  4 99]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [128]:
import numpy
a=numpy.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(numpy.hsplit(a,2))

[array([[1, 2, 3],
       [7, 8, 9]]), array([[ 4,  5,  6],
       [10, 11, 12]])]


In [132]:
print(numpy.vsplit(a,2))

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


In [135]:
import numpy
a=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(numpy.mean(a,axis=1))
print(numpy.mean(a,axis=0))

[2. 5. 8.]
[4. 5. 6.]


In [144]:
import numpy
a=numpy.array([1,2,3,1,4,5,6])
w=numpy.array([1,1,1,1,1,1,1])
print(numpy.average(a))
print(numpy.median(a))
print(numpy.average(a,weights=w))

3.142857142857143
3.0
3.142857142857143
